#!/bin/bash
# Script: generate_refresh_report.sh
# Purpose: Generate full refresh summary report
# Author: ETL Team
# Date: 2026-03-03

REFRESH_START_DATE=$1
REPORT_DIR="${REPORT_DIR:-/reports/informatica}"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
REPORT_FILE="${REPORT_DIR}/full_refresh_report_${TIMESTAMP}.txt"

mkdir -p "${REPORT_DIR}"

echo "Generating full refresh report..."

cat > "${REPORT_FILE}" <<EOF
================================================================================
                    FULL REFRESH SUMMARY REPORT
================================================================================

Refresh Date: ${REFRESH_START_DATE}
Report Generated: $(date)
Generated By: $(whoami)

================================================================================
                         DATA LOAD SUMMARY
================================================================================

EOF

# Get counts from database
psql -U ${DB_USER:-etl_user} -d ${DB_NAME:-datawarehouse} -t -A -F'|' <<SQLEOF >> "${REPORT_FILE}"

\echo 'TABLE|RECORD_COUNT|LOAD_STATUS'
\echo '------|------------|------------'

SELECT 'DIM_CUSTOMER (Current)' as table_name,
       COUNT(*) as record_count,
       'COMPLETED' as status
FROM DIM_CUSTOMER WHERE IS_CURRENT = 'Y'
UNION ALL
SELECT 'DIM_PRODUCT',
       COUNT(*),
       'COMPLETED'
FROM DIM_PRODUCT
UNION ALL
SELECT 'FACT_SALES',
       COUNT(*),
       'COMPLETED'
FROM FACT_SALES;

SQLEOF

cat >> "${REPORT_FILE}" <<EOF

================================================================================
                      PERFORMANCE METRICS
================================================================================

Workflow: wf_FULL_REFRESH
Start Time: ${REFRESH_START_DATE}
End Time: $(date)
Duration: [Calculated from workflow logs]

EOF

psql -U ${DB_USER:-etl_user} -d ${DB_NAME:-datawarehouse} -t <<SQLEOF >> "${REPORT_FILE}"

\echo 'Data Quality Metrics:'
\echo '---------------------'

SELECT 'Total Sales Amount: ' || TO_CHAR(SUM(TOTAL_AMOUNT), 'FM\$999,999,999.00')
FROM FACT_SALES;

SELECT 'Total Profit: ' || TO_CHAR(SUM(PROFIT_AMOUNT), 'FM\$999,999,999.00')
FROM FACT_SALES;

SELECT 'Average Profit Margin: ' || TO_CHAR(AVG(PROFIT_MARGIN_PERCENT), 'FM990.00') || '%'
FROM FACT_SALES;

SQLEOF

cat >> "${REPORT_FILE}" <<EOF

================================================================================
                       DATA QUALITY CHECKS
================================================================================

EOF

psql -U ${DB_USER:-etl_user} -d ${DB_NAME:-datawarehouse} -t <<SQLEOF >> "${REPORT_FILE}"

SELECT 'Duplicate Current Customers: ' || COUNT(*)
FROM (
    SELECT CUSTOMER_ID FROM DIM_CUSTOMER WHERE IS_CURRENT = 'Y'
    GROUP BY CUSTOMER_ID HAVING COUNT(*) > 1
) dups;

SELECT 'Products with Negative Prices: ' || COUNT(*)
FROM DIM_PRODUCT WHERE UNIT_PRICE < 0 OR COST_PRICE < 0;

SELECT 'Orphan Sales Records: ' || COUNT(*)
FROM FACT_SALES fs
WHERE NOT EXISTS (SELECT 1 FROM DIM_CUSTOMER dc WHERE dc.CUSTOMER_KEY = fs.CUSTOMER_KEY)
   OR NOT EXISTS (SELECT 1 FROM DIM_PRODUCT dp WHERE dp.PRODUCT_KEY = fs.PRODUCT_KEY);

SQLEOF

cat >> "${REPORT_FILE}" <<EOF

================================================================================
                           RECOMMENDATIONS
================================================================================

1. Review data quality check results above
2. Verify record counts match expected volumes
3. Check for any anomalies in sales metrics
4. Validate referential integrity (should be 0 orphans)
5. Update documentation if schema changes were made

================================================================================
                              SIGN-OFF
================================================================================

ETL Developer: _____________________  Date: ___________

QA Lead: ___________________________  Date: ___________

DBA: _______________________________  Date: ___________

================================================================================
                           END OF REPORT
================================================================================
EOF

echo "Report generated: ${REPORT_FILE}"
cat "${REPORT_FILE}"

exit 0
