-- =============================================
-- Staging Tables for ETL Process
-- Purpose: Temporary storage for source data
-- =============================================

-- Drop existing staging tables
DROP TABLE IF EXISTS STG_CUSTOMER;
DROP TABLE IF EXISTS STG_PRODUCT;
DROP TABLE IF EXISTS STG_SALES;

-- Staging table for Customer data
CREATE TABLE STG_CUSTOMER (
    CUSTOMER_ID VARCHAR(50),
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    EMAIL VARCHAR(200),
    PHONE VARCHAR(20),
    ADDRESS VARCHAR(500),
    CITY VARCHAR(100),
    STATE VARCHAR(50),
    ZIP_CODE VARCHAR(20),
    COUNTRY VARCHAR(100),
    REGISTRATION_DATE DATE,
    CUSTOMER_TYPE VARCHAR(50),
    LOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    SOURCE_SYSTEM VARCHAR(50) DEFAULT 'CSV_FILE'
);

-- Staging table for Product data
CREATE TABLE STG_PRODUCT (
    PRODUCT_ID VARCHAR(50),
    PRODUCT_NAME VARCHAR(200),
    CATEGORY VARCHAR(100),
    SUB_CATEGORY VARCHAR(100),
    BRAND VARCHAR(100),
    UNIT_PRICE DECIMAL(10,2),
    COST_PRICE DECIMAL(10,2),
    SUPPLIER_ID VARCHAR(50),
    STOCK_QUANTITY INTEGER,
    PRODUCT_STATUS VARCHAR(20),
    LOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    SOURCE_SYSTEM VARCHAR(50) DEFAULT 'CSV_FILE'
);

-- Staging table for Sales Transactions
CREATE TABLE STG_SALES (
    TRANSACTION_ID VARCHAR(50),
    TRANSACTION_DATE TIMESTAMP,
    CUSTOMER_ID VARCHAR(50),
    PRODUCT_ID VARCHAR(50),
    QUANTITY INTEGER,
    UNIT_PRICE DECIMAL(10,2),
    DISCOUNT_PERCENT DECIMAL(5,2),
    TAX_AMOUNT DECIMAL(10,2),
    TOTAL_AMOUNT DECIMAL(10,2),
    PAYMENT_METHOD VARCHAR(50),
    STORE_ID VARCHAR(50),
    REGION VARCHAR(50),
    LOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    SOURCE_SYSTEM VARCHAR(50) DEFAULT 'CSV_FILE'
);

-- Create indexes for better performance
CREATE INDEX IDX_STG_CUSTOMER_ID ON STG_CUSTOMER(CUSTOMER_ID);
CREATE INDEX IDX_STG_PRODUCT_ID ON STG_PRODUCT(PRODUCT_ID);
CREATE INDEX IDX_STG_SALES_TXN ON STG_SALES(TRANSACTION_ID);
CREATE INDEX IDX_STG_SALES_CUST ON STG_SALES(CUSTOMER_ID);
CREATE INDEX IDX_STG_SALES_PROD ON STG_SALES(PRODUCT_ID);

COMMIT;
