-- =============================================
-- Dimension Tables for Data Warehouse
-- Purpose: Store descriptive attributes
-- SCD Type 2 implementation for history tracking
-- =============================================

-- Drop existing dimension tables
DROP TABLE IF EXISTS DIM_CUSTOMER;
DROP TABLE IF EXISTS DIM_PRODUCT;
DROP TABLE IF EXISTS DIM_DATE;

-- Customer Dimension (SCD Type 2)
CREATE TABLE DIM_CUSTOMER (
    CUSTOMER_KEY INTEGER PRIMARY KEY,
    CUSTOMER_ID VARCHAR(50) NOT NULL,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    FULL_NAME VARCHAR(200),
    EMAIL VARCHAR(200),
    PHONE VARCHAR(20),
    ADDRESS VARCHAR(500),
    CITY VARCHAR(100),
    STATE VARCHAR(50),
    ZIP_CODE VARCHAR(20),
    COUNTRY VARCHAR(100),
    REGISTRATION_DATE DATE,
    CUSTOMER_TYPE VARCHAR(50),
    -- SCD Type 2 columns
    EFFECTIVE_FROM_DATE DATE NOT NULL,
    EFFECTIVE_TO_DATE DATE DEFAULT '9999-12-31',
    IS_CURRENT CHAR(1) DEFAULT 'Y',
    -- Audit columns
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    SOURCE_SYSTEM VARCHAR(50)
);

-- Product Dimension (SCD Type 1)
CREATE TABLE DIM_PRODUCT (
    PRODUCT_KEY INTEGER PRIMARY KEY,
    PRODUCT_ID VARCHAR(50) NOT NULL UNIQUE,
    PRODUCT_NAME VARCHAR(200),
    CATEGORY VARCHAR(100),
    SUB_CATEGORY VARCHAR(100),
    BRAND VARCHAR(100),
    UNIT_PRICE DECIMAL(10,2),
    COST_PRICE DECIMAL(10,2),
    PROFIT_MARGIN DECIMAL(5,2),
    SUPPLIER_ID VARCHAR(50),
    STOCK_QUANTITY INTEGER,
    PRODUCT_STATUS VARCHAR(20),
    -- Audit columns
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    SOURCE_SYSTEM VARCHAR(50)
);

-- Date Dimension (Pre-populated)
CREATE TABLE DIM_DATE (
    DATE_KEY INTEGER PRIMARY KEY,
    FULL_DATE DATE NOT NULL UNIQUE,
    DAY_OF_WEEK INTEGER,
    DAY_NAME VARCHAR(20),
    DAY_OF_MONTH INTEGER,
    DAY_OF_YEAR INTEGER,
    WEEK_OF_YEAR INTEGER,
    MONTH_NUMBER INTEGER,
    MONTH_NAME VARCHAR(20),
    QUARTER_NUMBER INTEGER,
    QUARTER_NAME VARCHAR(10),
    YEAR INTEGER,
    IS_WEEKEND CHAR(1),
    IS_HOLIDAY CHAR(1),
    FISCAL_YEAR INTEGER,
    FISCAL_QUARTER INTEGER
);

-- Create indexes
CREATE INDEX IDX_DIM_CUSTOMER_ID ON DIM_CUSTOMER(CUSTOMER_ID);
CREATE INDEX IDX_DIM_CUSTOMER_CURRENT ON DIM_CUSTOMER(IS_CURRENT);
CREATE INDEX IDX_DIM_PRODUCT_ID ON DIM_PRODUCT(PRODUCT_ID);
CREATE INDEX IDX_DIM_PRODUCT_CATEGORY ON DIM_PRODUCT(CATEGORY);
CREATE INDEX IDX_DIM_DATE_FULL ON DIM_DATE(FULL_DATE);

-- Create sequences for surrogate keys
CREATE SEQUENCE SEQ_CUSTOMER_KEY START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PRODUCT_KEY START WITH 1 INCREMENT BY 1;

COMMIT;
