-- =============================================
-- Fact Tables for Data Warehouse
-- Purpose: Store measurable business metrics
-- =============================================

-- Drop existing fact tables
DROP TABLE IF EXISTS FACT_SALES;
DROP TABLE IF EXISTS FACT_SALES_DAILY_AGG;

-- Sales Fact Table (Transaction Grain)
CREATE TABLE FACT_SALES (
    SALES_KEY BIGINT PRIMARY KEY,
    TRANSACTION_ID VARCHAR(50) NOT NULL UNIQUE,
    DATE_KEY INTEGER NOT NULL,
    CUSTOMER_KEY INTEGER NOT NULL,
    PRODUCT_KEY INTEGER NOT NULL,
    STORE_ID VARCHAR(50),
    REGION VARCHAR(50),
    -- Measures
    QUANTITY INTEGER,
    UNIT_PRICE DECIMAL(10,2),
    DISCOUNT_PERCENT DECIMAL(5,2),
    DISCOUNT_AMOUNT DECIMAL(10,2),
    TAX_AMOUNT DECIMAL(10,2),
    TOTAL_AMOUNT DECIMAL(10,2),
    COST_AMOUNT DECIMAL(10,2),
    PROFIT_AMOUNT DECIMAL(10,2),
    PROFIT_MARGIN_PERCENT DECIMAL(5,2),
    PAYMENT_METHOD VARCHAR(50),
    -- Audit columns
    LOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    SOURCE_SYSTEM VARCHAR(50),
    -- Foreign keys
    CONSTRAINT FK_SALES_DATE FOREIGN KEY (DATE_KEY) REFERENCES DIM_DATE(DATE_KEY),
    CONSTRAINT FK_SALES_CUSTOMER FOREIGN KEY (CUSTOMER_KEY) REFERENCES DIM_CUSTOMER(CUSTOMER_KEY),
    CONSTRAINT FK_SALES_PRODUCT FOREIGN KEY (PRODUCT_KEY) REFERENCES DIM_PRODUCT(PRODUCT_KEY)
);

-- Daily Sales Aggregate Fact Table
CREATE TABLE FACT_SALES_DAILY_AGG (
    AGG_KEY BIGINT PRIMARY KEY,
    DATE_KEY INTEGER NOT NULL,
    PRODUCT_KEY INTEGER NOT NULL,
    REGION VARCHAR(50),
    -- Aggregated Measures
    TOTAL_TRANSACTIONS INTEGER,
    TOTAL_QUANTITY INTEGER,
    TOTAL_SALES_AMOUNT DECIMAL(15,2),
    TOTAL_DISCOUNT_AMOUNT DECIMAL(15,2),
    TOTAL_TAX_AMOUNT DECIMAL(15,2),
    TOTAL_COST_AMOUNT DECIMAL(15,2),
    TOTAL_PROFIT_AMOUNT DECIMAL(15,2),
    AVG_TRANSACTION_VALUE DECIMAL(10,2),
    AVG_PROFIT_MARGIN DECIMAL(5,2),
    -- Audit columns
    LOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    -- Foreign keys
    CONSTRAINT FK_AGG_DATE FOREIGN KEY (DATE_KEY) REFERENCES DIM_DATE(DATE_KEY),
    CONSTRAINT FK_AGG_PRODUCT FOREIGN KEY (PRODUCT_KEY) REFERENCES DIM_PRODUCT(PRODUCT_KEY)
);

-- Create indexes for performance
CREATE INDEX IDX_FACT_SALES_DATE ON FACT_SALES(DATE_KEY);
CREATE INDEX IDX_FACT_SALES_CUSTOMER ON FACT_SALES(CUSTOMER_KEY);
CREATE INDEX IDX_FACT_SALES_PRODUCT ON FACT_SALES(PRODUCT_KEY);
CREATE INDEX IDX_FACT_SALES_REGION ON FACT_SALES(REGION);
CREATE INDEX IDX_FACT_SALES_LOAD ON FACT_SALES(LOAD_DATE);

CREATE INDEX IDX_FACT_AGG_DATE ON FACT_SALES_DAILY_AGG(DATE_KEY);
CREATE INDEX IDX_FACT_AGG_PRODUCT ON FACT_SALES_DAILY_AGG(PRODUCT_KEY);
CREATE INDEX IDX_FACT_AGG_REGION ON FACT_SALES_DAILY_AGG(REGION);

-- Create sequence for surrogate keys
CREATE SEQUENCE SEQ_SALES_KEY START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_AGG_KEY START WITH 1 INCREMENT BY 1;

COMMIT;
