-- =============================================
-- Control Tables for ETL Process Management
-- Purpose: Track ETL execution, errors, and metrics
-- =============================================

-- Drop existing control tables
DROP TABLE IF EXISTS ETL_CONTROL_LOG;
DROP TABLE IF EXISTS ETL_ERROR_LOG;
DROP TABLE IF EXISTS ETL_PERFORMANCE_STATS;
DROP TABLE IF EXISTS ETL_DATA_QUALITY_LOG;

-- ETL Control Log - Track workflow execution
CREATE TABLE ETL_CONTROL_LOG (
    LOG_ID BIGINT PRIMARY KEY,
    WORKFLOW_NAME VARCHAR(200) NOT NULL,
    SESSION_NAME VARCHAR(200),
    WORKFLOW_RUN_ID INTEGER,
    START_TIME TIMESTAMP NOT NULL,
    END_TIME TIMESTAMP,
    STATUS VARCHAR(50),
    ROWS_READ INTEGER,
    ROWS_LOADED INTEGER,
    ROWS_REJECTED INTEGER,
    ERROR_MESSAGE VARCHAR(4000),
    CREATED_BY VARCHAR(100) DEFAULT 'INFORMATICA',
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ETL Error Log - Track data errors and rejections
CREATE TABLE ETL_ERROR_LOG (
    ERROR_ID BIGINT PRIMARY KEY,
    LOG_ID BIGINT,
    SESSION_NAME VARCHAR(200),
    ERROR_TYPE VARCHAR(100),
    ERROR_MESSAGE VARCHAR(4000),
    SOURCE_TABLE VARCHAR(200),
    TARGET_TABLE VARCHAR(200),
    REJECTED_DATA VARCHAR(4000),
    ERROR_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ERROR_LOG FOREIGN KEY (LOG_ID) REFERENCES ETL_CONTROL_LOG(LOG_ID)
);

-- ETL Performance Stats - Track performance metrics
CREATE TABLE ETL_PERFORMANCE_STATS (
    STAT_ID BIGINT PRIMARY KEY,
    LOG_ID BIGINT,
    SESSION_NAME VARCHAR(200) NOT NULL,
    MAPPING_NAME VARCHAR(200),
    EXECUTION_DATE DATE NOT NULL,
    DURATION_SECONDS INTEGER,
    ROWS_PROCESSED INTEGER,
    THROUGHPUT_ROWS_PER_SEC INTEGER,
    SOURCE_READ_TIME_SEC INTEGER,
    TRANSFORMATION_TIME_SEC INTEGER,
    TARGET_LOAD_TIME_SEC INTEGER,
    PARTITION_COUNT INTEGER,
    SERVER_NAME VARCHAR(100),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PERF_LOG FOREIGN KEY (LOG_ID) REFERENCES ETL_CONTROL_LOG(LOG_ID)
);

-- ETL Data Quality Log - Track data quality issues
CREATE TABLE ETL_DATA_QUALITY_LOG (
    DQ_ID BIGINT PRIMARY KEY,
    LOG_ID BIGINT,
    CHECK_DATE DATE NOT NULL,
    TABLE_NAME VARCHAR(200) NOT NULL,
    COLUMN_NAME VARCHAR(200),
    DQ_RULE VARCHAR(500),
    RECORDS_CHECKED INTEGER,
    RECORDS_FAILED INTEGER,
    FAIL_PERCENTAGE DECIMAL(5,2),
    SEVERITY VARCHAR(20),
    STATUS VARCHAR(50),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_DQ_LOG FOREIGN KEY (LOG_ID) REFERENCES ETL_CONTROL_LOG(LOG_ID)
);

-- Create indexes
CREATE INDEX IDX_CONTROL_WORKFLOW ON ETL_CONTROL_LOG(WORKFLOW_NAME, START_TIME);
CREATE INDEX IDX_CONTROL_STATUS ON ETL_CONTROL_LOG(STATUS);
CREATE INDEX IDX_ERROR_SESSION ON ETL_ERROR_LOG(SESSION_NAME);
CREATE INDEX IDX_ERROR_TIME ON ETL_ERROR_LOG(ERROR_TIMESTAMP);
CREATE INDEX IDX_PERF_SESSION ON ETL_PERFORMANCE_STATS(SESSION_NAME);
CREATE INDEX IDX_PERF_DATE ON ETL_PERFORMANCE_STATS(EXECUTION_DATE);
CREATE INDEX IDX_DQ_TABLE ON ETL_DATA_QUALITY_LOG(TABLE_NAME);
CREATE INDEX IDX_DQ_DATE ON ETL_DATA_QUALITY_LOG(CHECK_DATE);

-- Create sequences
CREATE SEQUENCE SEQ_LOG_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ERROR_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_STAT_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DQ_ID START WITH 1 INCREMENT BY 1;

COMMIT;
